
let colorflow = (rgb, side, off) => {
  if(side == 'left'||side == 'both'){
		sendToArduino('/l0lr', rgb.ls.r)
    sendToArduino('/l0lg', rgb.ls.g)
    sendToArduino('/l0lb', rgb.ls.b)
		setTimeout(function(){sendToArduino('/l1lr', rgb.ls.r)}, 100)
		setTimeout(function(){sendToArduino('/l1lg', rgb.ls.g)}, 100)
		setTimeout(function(){sendToArduino('/l1lb', rgb.ls.b)}, 100)
    setTimeout(function(){sendToArduino('/l2lr', rgb.ls.r)}, 200)
		setTimeout(function(){sendToArduino('/l2lg', rgb.ls.g)}, 200)
		setTimeout(function(){sendToArduino('/l2lb', rgb.ls.b)}, 200)
    setTimeout(function(){sendToArduino('/l3lr', rgb.ls.r)}, 300)
    setTimeout(function(){sendToArduino('/l3lg', rgb.ls.g)}, 300)
    setTimeout(function(){sendToArduino('/l3lb', rgb.ls.b)}, 300)
    // setTimeout(function(){sendToArduino('/l4lr', rgb.ls.r)}, 200)
    // setTimeout(function(){sendToArduino('/l4lg', rgb.ls.g)}, 200)
    // setTimeout(function(){sendToArduino('/l4lb', rgb.ls.b)}, 200)
    // setTimeout(function(){sendToArduino('/l5lr', rgb.ls.r)}, 250)
    // setTimeout(function(){sendToArduino('/l5lg', rgb.ls.g)}, 250)
    // setTimeout(function(){sendToArduino('/l5lb', rgb.ls.b)}, 250)
    // setTimeout(function(){sendToArduino('/l6lr', rgb.ls.r)}, 300)
    // setTimeout(function(){sendToArduino('/l6lg', rgb.ls.g)}, 300)
    // setTimeout(function(){sendToArduino('/l6lb', rgb.ls.b)}, 300)
    // setTimeout(function(){sendToArduino('/l7lr', rgb.ls.r)}, 350)
    // setTimeout(function(){sendToArduino('/l7lg', rgb.ls.g)}, 350)
    // setTimeout(function(){sendToArduino('/l7lb', rgb.ls.b)}, 350)
    // setTimeout(function(){sendToArduino('/l8lr', rgb.ls.r)}, 400)
    // setTimeout(function(){sendToArduino('/l8lg', rgb.ls.g)}, 400)
    // setTimeout(function(){sendToArduino('/l8lb', rgb.ls.b)}, 400)
    // setTimeout(function(){sendToArduino('/l9lr', rgb.ls.r)}, 450)
    // setTimeout(function(){sendToArduino('/l9lg', rgb.ls.g)}, 450)
    // setTimeout(function(){sendToArduino('/l9lb', rgb.ls.b)}, 450)
    if (off){
      setTimeout(function(){sendToArduino('/l0lr', 0)}, 200)
  		setTimeout(function(){sendToArduino('/l0lg', 0)}, 200)
  		setTimeout(function(){sendToArduino('/l0lb', 0)}, 200)
      setTimeout(function(){sendToArduino('/l1lr', 0)}, 300)
  		setTimeout(function(){sendToArduino('/l1lg', 0)}, 300)
  		setTimeout(function(){sendToArduino('/l1lb', 0)}, 300)
      setTimeout(function(){sendToArduino('/l2lr', 0)}, 400)
  		setTimeout(function(){sendToArduino('/l2lg', 0)}, 400)
  		setTimeout(function(){sendToArduino('/l2lb', 0)}, 400)
      setTimeout(function(){sendToArduino('/l3lr', 0)}, 500)
      setTimeout(function(){sendToArduino('/l3lg', 0)}, 500)
      setTimeout(function(){sendToArduino('/l3lb', 0)}, 500)
      // setTimeout(function(){sendToArduino('/l4lr', 0)}, 300)
      // setTimeout(function(){sendToArduino('/l4lg', 0)}, 300)
      // setTimeout(function(){sendToArduino('/l4lb', 0)}, 300)
      // setTimeout(function(){sendToArduino('/l5lr', 0)}, 350)
      // setTimeout(function(){sendToArduino('/l5lg', 0)}, 350)
      // setTimeout(function(){sendToArduino('/l5lb', 0)}, 350)
      // setTimeout(function(){sendToArduino('/l6lr', 0)}, 400)
      // setTimeout(function(){sendToArduino('/l6lg', 0)}, 400)
      // setTimeout(function(){sendToArduino('/l6lb', 0)}, 400)
      // setTimeout(function(){sendToArduino('/l7lr', 0)}, 450)
      // setTimeout(function(){sendToArduino('/l7lg', 0)}, 450)
      // setTimeout(function(){sendToArduino('/l7lb', 0)}, 450)
      // setTimeout(function(){sendToArduino('/l8lr', 0)}, 500)
      // setTimeout(function(){sendToArduino('/l8lg', 0)}, 500)
      // setTimeout(function(){sendToArduino('/l8lb', 0)}, 500)
      // setTimeout(function(){sendToArduino('/l9lr', 0)}, 550)
      // setTimeout(function(){sendToArduino('/l9lg', 0)}, 550)
      // setTimeout(function(){sendToArduino('/l9lb', 0)}, 550)
    }
	}
	if(side == 'right'||side == 'both'){
    sendToArduino('/r0lr', rgb.rs.r)
    sendToArduino('/r0lg', rgb.rs.g)
    sendToArduino('/r0lb', rgb.rs.b)
		setTimeout(function(){sendToArduino('/r1lr', rgb.rs.r)}, 100)
		setTimeout(function(){sendToArduino('/r1lg', rgb.rs.g)}, 100)
		setTimeout(function(){sendToArduino('/r1lb', rgb.rs.b)}, 100)
    setTimeout(function(){sendToArduino('/r2lr', rgb.rs.r)}, 200)
    setTimeout(function(){sendToArduino('/r2lg', rgb.rs.g)}, 200)
    setTimeout(function(){sendToArduino('/r2lb', rgb.rs.b)}, 200)
    setTimeout(function(){sendToArduino('/r3lr', rgb.rs.r)}, 300)
    setTimeout(function(){sendToArduino('/r3lg', rgb.rs.g)}, 300)
    setTimeout(function(){sendToArduino('/r3lb', rgb.rs.b)}, 300)
    // setTimeout(function(){sendToArduino('/r4lr', rgb.rs.r)}, 200)
    // setTimeout(function(){sendToArduino('/r4lg', rgb.rs.g)}, 200)
    // setTimeout(function(){sendToArduino('/r4lb', rgb.rs.b)}, 200)
    // setTimeout(function(){sendToArduino('/r5lr', rgb.rs.r)}, 250)
    // setTimeout(function(){sendToArduino('/r5lg', rgb.rs.g)}, 250)
    // setTimeout(function(){sendToArduino('/r5lb', rgb.rs.b)}, 250)
    // setTimeout(function(){sendToArduino('/r6lr', rgb.rs.r)}, 300)
    // setTimeout(function(){sendToArduino('/r6lg', rgb.rs.g)}, 300)
    // setTimeout(function(){sendToArduino('/r6lb', rgb.rs.b)}, 300)
    // setTimeout(function(){sendToArduino('/r7lr', rgb.rs.r)}, 350)
    // setTimeout(function(){sendToArduino('/r7lg', rgb.rs.g)}, 350)
    // setTimeout(function(){sendToArduino('/r7lb', rgb.rs.b)}, 350)
    // setTimeout(function(){sendToArduino('/r8lr', rgb.rs.r)}, 400)
    // setTimeout(function(){sendToArduino('/r8lg', rgb.rs.g)}, 400)
    // setTimeout(function(){sendToArduino('/r8lb', rgb.rs.b)}, 400)
    // setTimeout(function(){sendToArduino('/r9lr', rgb.rs.r)}, 450)
    // setTimeout(function(){sendToArduino('/r9lg', rgb.rs.g)}, 450)
    // setTimeout(function(){sendToArduino('/r9lb', rgb.rs.b)}, 450)
    if (off){
      setTimeout(function(){sendToArduino('/r0lr', 0)}, 100)
      setTimeout(function(){sendToArduino('/r0lg', 0)}, 100)
      setTimeout(function(){sendToArduino('/r0lb', 0)}, 100)
      setTimeout(function(){sendToArduino('/r1lr', 0)}, 200)
      setTimeout(function(){sendToArduino('/r1lg', 0)}, 200)
      setTimeout(function(){sendToArduino('/r1lb', 0)}, 200)
      setTimeout(function(){sendToArduino('/r2lr', 0)}, 300)
      setTimeout(function(){sendToArduino('/r2lg', 0)}, 300)
      setTimeout(function(){sendToArduino('/r2lb', 0)}, 300)
      setTimeout(function(){sendToArduino('/r3lr', 0)}, 400)
      setTimeout(function(){sendToArduino('/r3lg', 0)}, 400)
      setTimeout(function(){sendToArduino('/r3lb', 0)}, 400)
      // setTimeout(function(){sendToArduino('/r4lr', 0)}, 300)
      // setTimeout(function(){sendToArduino('/r4lg', 0)}, 300)
      // setTimeout(function(){sendToArduino('/r4lb', 0)}, 300)
      // setTimeout(function(){sendToArduino('/r5lr', 0)}, 350)
      // setTimeout(function(){sendToArduino('/r5lg', 0)}, 350)
      // setTimeout(function(){sendToArduino('/r5lb', 0)}, 350)
      // setTimeout(function(){sendToArduino('/r6lr', 0)}, 400)
      // setTimeout(function(){sendToArduino('/r6lg', 0)}, 400)
      // setTimeout(function(){sendToArduino('/r6lb', 0)}, 400)
      // setTimeout(function(){sendToArduino('/r7lr', 0)}, 450)
      // setTimeout(function(){sendToArduino('/r7lg', 0)}, 450)
      // setTimeout(function(){sendToArduino('/r7lb', 0)}, 450)
      // setTimeout(function(){sendToArduino('/r8lr', 0)}, 500)
      // setTimeout(function(){sendToArduino('/r8lg', 0)}, 500)
      // setTimeout(function(){sendToArduino('/r8lb', 0)}, 500)
      // setTimeout(function(){sendToArduino('/r9lr', 0)}, 550)
      // setTimeout(function(){sendToArduino('/r9lg', 0)}, 550)
      // setTimeout(function(){sendToArduino('/r9lb', 0)}, 550)
    }
	}
}
module.exports = colorflow
